services:
  # 1. MySQL Database
  lms-mysql:
    image: mysql:8.4.3
    container_name: lms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ExLMS
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. MinIO (File Storage)
  lms-minio:
    image: quay.io/minio/minio
    container_name: lms-minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # 3. Backend Service (Spring Boot)
  lms-backend:
    build:
      context: ./ExLMS-BE
      dockerfile: Dockerfile
    image: mingfang914/exlms-backend:latest
    container_name: lms-backend
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_URL=http://lms-minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - lms-mysql
      - lms-minio
    ports:
      - "8081:8081"

  # 4. Frontend Service (React/Vite served via Nginx)
  lms-frontend:
    build:
      context: ./ExLMS-FE
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    image: mingfang914/exlms-frontend:latest
    container_name: lms-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - lms-backend

  # 5. Database Admin Tool (phpMyAdmin)
  lms-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lms-phpmyadmin
    restart: always
    environment:
      PMA_HOST: lms-mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - lms-mysql

volumes:
  mysql_data:
  minio_data: