spring.application.name=ExLMS
server.port=8081

# 2. MySQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ExLMS?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&connectionCollation=utf8mb4_unicode_ci}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=BINARY



# 5. MinIO Configuration
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=lms-files
minio.resource-bucket=lms-resources

# 6. Upload Configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 7. Security Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY:VGhpcy1pcy1hLXZlcnktc2VjdXJlLWtleS1mb3ItZXhsbXMtYmFja2VuZC1wcm9qZWN0LXRlYW0tZml2ZQ==}
